version: '3.6'

volumes:
  postgres_volume:

services:
  front:
    build: ./infra/nginx
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html

  php:
    build: ./infra/php
    volumes:
      - ./www:/var/www/html

  postgres:
    build: ./infra/postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db




